# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Image-Magick-Stencilize
version:      1.02
version_from: lib/Image/Magick/Stencilize.pm
installdirs:  site
requires:
    Image::Magick:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
